dbMemo "SQL" ="SELECT mm.TX_DATEDELIVERY as TX_DATE FROM t_q_material_movement AS mm WHERE mm.T"
    "X_DATEDELIVERY is not null  AND (mm.D_MATERIALNAME like '%H0801/DT/PST-VIII/2023"
    "%') OR (mm.TX_PO like '%H0801/DT/PST-VIII/2023%') OR (mm.TX_ORIGIN like '%H0801/"
    "DT/PST-VIII/2023%') OR (mm.TX_DESTINATION like '%H0801/DT/PST-VIII/2023%') OR (m"
    "m.TX_MANIFEST like '%H0801/DT/PST-VIII/2023%')  UNION SELECT mm.TX_DATERECEIVED "
    "as TX_DATE  FROM t_q_material_movement AS mm WHERE mm.TX_DATERECEIVED is not nul"
    "l  AND (mm.D_MATERIALNAME like '%H0801/DT/PST-VIII/2023%') OR (mm.TX_PO like '%H"
    "0801/DT/PST-VIII/2023%') OR (mm.TX_ORIGIN like '%H0801/DT/PST-VIII/2023%') OR (m"
    "m.TX_DESTINATION like '%H0801/DT/PST-VIII/2023%') OR (mm.TX_MANIFEST like '%H080"
    "1/DT/PST-VIII/2023%')  GROUP BY mm.TX_DATEDELIVERY, mm.TX_DATERECEIVED\015\012OR"
    "DER BY TX_DATE DESC;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="-1"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbMemo "OrderBy" ="[q_mat_datemove].TX_DATE DESC"
Begin
    Begin
        dbText "Name" ="TX_DATE"
        dbLong "AggregateType" ="-1"
    End
End
